# Generated by Django 4.0 on 2021-12-10 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('received_date', models.DateField(default=datetime.date.today, verbose_name='дата поступления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена')),
                ('unit', models.CharField(max_length=10, verbose_name='единица измерения')),
                ('vendor_name', models.CharField(max_length=255, verbose_name='имя поставщика')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
